uid_dict = {'5197409175': {'origin_weibo_number': 168,
 'retweeted_weibo_comment_total_number': 23,
 'origin_weibo_retweeted_brust_average': 27,
 'retweeted_weibo_retweeted_total_number': 46,
 'retweeted_weibo_retweeted_brust_average': 46,
 'origin_weibo_comment_total_number': 805,
 'retweeted_weibo_number': 35,
 'origin_weibo_comment_brust_average': 36,
 'comment_weibo_number': 130,
 'origin_weibo_retweeted_total_number': 1036},

 '2550548823': {'origin_weibo_number': 99,
 'retweeted_weibo_comment_total_number': 44,
 'origin_weibo_retweeted_brust_average': 236,
 'retweeted_weibo_retweeted_total_number': 22,
 'retweeted_weibo_retweeted_brust_average': 10,
 'origin_weibo_comment_total_number': 2597,
 'retweeted_weibo_number': 167,
 'origin_weibo_comment_brust_average': 342,
 'comment_weibo_number': 42,
 'origin_weibo_retweeted_total_number': 61},

 '1650111241': {'origin_weibo_number': 86,
 'retweeted_weibo_comment_total_number': 5,
 'origin_weibo_retweeted_brust_average': 198,
 'retweeted_weibo_retweeted_total_number': 490,
 'retweeted_weibo_retweeted_brust_average': 25,
 'origin_weibo_comment_total_number': 1160,
 'retweeted_weibo_number': 78,
 'origin_weibo_comment_brust_average': 1,
 'comment_weibo_number': 112,
 'origin_weibo_retweeted_total_number': 506},

 '1229384444': {'origin_weibo_number': 101,
 'retweeted_weibo_comment_total_number': 19,
 'origin_weibo_retweeted_brust_average': 16,
 'retweeted_weibo_retweeted_total_number': 27,
 'retweeted_weibo_retweeted_brust_average': 9,
 'origin_weibo_comment_total_number': 1613,
 'retweeted_weibo_number': 88,
 'origin_weibo_comment_brust_average': 344,
 'comment_weibo_number': 43,
 'origin_weibo_retweeted_total_number': 2681},

 '2449456027': {'origin_weibo_number': 100,
 'retweeted_weibo_comment_total_number': 12,
 'origin_weibo_retweeted_brust_average': 35,
 'retweeted_weibo_retweeted_total_number': 18,
 'retweeted_weibo_retweeted_brust_average': 20,
 'origin_weibo_comment_total_number': 1200,
 'retweeted_weibo_number': 165,
 'origin_weibo_comment_brust_average': 218,
 'comment_weibo_number': 9,
 'origin_weibo_retweeted_total_number': 550},

 '1433239854': {'origin_weibo_number': 41,
 'retweeted_weibo_comment_total_number': 19,
 'origin_weibo_retweeted_brust_average': 331,
 'retweeted_weibo_retweeted_total_number': 35,
 'retweeted_weibo_retweeted_brust_average': 19,
 'origin_weibo_comment_total_number': 2849,
 'retweeted_weibo_number': 136,
 'origin_weibo_comment_brust_average': 106,
 'comment_weibo_number': 122,
 'origin_weibo_retweeted_total_number': 4091},

 '1615931613': {'origin_weibo_number': 111,
 'retweeted_weibo_comment_total_number': 8,
 'origin_weibo_retweeted_brust_average': 220,
 'retweeted_weibo_retweeted_total_number': 10,
 'retweeted_weibo_retweeted_brust_average': 50,
 'origin_weibo_comment_total_number': 6766,
 'retweeted_weibo_number': 181,
 'origin_weibo_comment_brust_average': 244,
 'comment_weibo_number': 137,
 'origin_weibo_retweeted_total_number': 1524}}